Add potential observer
iv4n-t3a/lamp-of-god pull request #3
Opened 2024-11-26 19:09 UTC by anishchenkoivan

2024-11-26 21:00 UTC, iv4n-t3a requested changes

2024-11-26 21:00 UTC, iv4n-t3a commented on CMakeLists.txt
> +        src/observers.cpp)
убери

2024-11-26 21:00 UTC, iv4n-t3a commented on src/tube.hpp
> +  virtual std::pair<dist_t, dist_t> GetDimensions() = 0;
Сделай vector

2024-11-26 21:00 UTC, iv4n-t3a commented on src/observers.cpp
> +      file_path_(file_path),
directory path

2024-11-26 21:00 UTC, iv4n-t3a commented on src/observers.cpp
> +        output_file << value.Len() << " ";
тогда и тут сделай пробел как `char`

2024-11-26 21:00 UTC, iv4n-t3a commented on src/observers.cpp
> +    std::ofstream output_file(file_path_ + "/" + std::to_string(time_passed_) + ".txt");
и тут

2024-11-26 21:01 UTC, anishchenkoivan commented on src/tube.hpp
> +  virtual std::pair<dist_t, dist_t> GetDimensions() = 0;
Nei

2024-11-26 21:10 UTC, iv4n-t3a approved these changes

2024-11-27 09:07 UTC, iv4n-t3a approved these changes

2024-11-27 09:08 UTC, merged